### PR TITLE
Add Object callback tests

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@danielmarbach repro in wire compat for the callbacks bug

**Comment by danielmarbach** [comment]
Shouldn't there be a reply somewhere?

**Comment by SimonCropp** [comment]
Eg https://github.com/Particular/NServiceBus.WireCompatibilityTests/blob/objectcallbacktests/Callbacks/Core_3_x/Handler.cs#L22

Am i missing  some?

**Comment by danielmarbach** [comment]
Strange I did not see this in the diff view. So it was existing code then.

**Comment by danielmarbach** [comment]
Pushed an update with the beta

**Comment by danielmarbach** [comment]
Nice!

**Pull request merged**
